### ISSUE TITLE
CodeMirror Dependencies

### ISSUE THREAD

**Issue by BenjaminPrice** [Clemens-E/obsidian-languagetool-plugin#43]
Since the changes added in #39 there are now multiple `@codemirror` files being imported but they're not rolled up into the plugin. As such, you cannot even enable the plugin.

```
app.js:1 Plugin failure: obsidian-languagetool-plugin Error: Cannot find module '@codemirror/tooltip'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (internal/modules/cjs/loader.js:887)
    at Function.o._resolveFilename (electron/js2c/renderer_init.js:33)
    at Module._load (internal/modules/cjs/loader.js:732)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at et (app.js:1)
    at r (app.js:1)
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:1:104)
```

**Comment by mgmeyers** [comment]
@BenjaminPrice Yes, this is intentional. The latest version of the plugin requires version 0.13.16 of obsidian which does supply the tooltip plugin. Are you on 0.13.15? If so, there may be an issue with the versioning, as it shouldn't allow you to install the plugin yet.

**Comment by BenjaminPrice** [comment]
Is 0.13.16 a beta/dev build? The latest I can find (and that I am running) for MacOS is 0.13.14. 

With my PR, it works fine on 0.13.14.

**Comment by mgmeyers** [comment]
@BenjaminPrice Yes, 0.13.16 is an insiders build. I've cut a release with your changes that should work on 0.13.14. You may have to uninstall and reinstall the plugin to pick up the right version. It should install version 0.1.6 of the language tool plugin. Let me know if you run into any issues with this

**Comment by mgmeyers** [comment]
Closing this, as it should no longer be an issue.
